### ISSUE TITLE
A list of all invalid filenames causes error

### ISSUE THREAD

**Issue by pkkid** [dstathis/optprompt#1]
Optprompt should still work if all files names specified do no exist. Since these files are used as default values, there is no reason any of them must exist.

**Comment by pkkid** [comment]
I was able to suppress the warning about non-existent files with the following code. However, if *all* files are non-existing, optprompt throws an exception.

```python
# Suppress toml missing file warnings
import warnings  # noqa
warnings.filterwarnings(action='ignore', module='.*toml.*')

**Comment by dstathis** [comment]
PR solves this.
